# Cloudflare Pages configuration
pages_build_output_dir = "out"
build.command = "node middleware-fix.js && SKIP_MIDDLEWARE_CHECK=1 npm run build"

[env]
NODE_VERSION = "18.12.0"
NEXT_PUBLIC_API_URL = "https://api.twincitiescoverage.com" 