# Cloudflare Pages configuration
pages_build_output_dir = "out"
build.command = "bash fix-middleware.sh && npm run build"

[env]
NODE_VERSION = "18.12.0"
NEXT_PUBLIC_API_URL = "https://api.twincitiescoverage.com" 