# Cloudflare Pages configuration
pages_build_output_dir = ".vercel/output/static"
build.command = "npx @cloudflare/next-on-pages@1"

[build.environment]
NODE_VERSION = "18.12.0"

[environment_variables]
NEXT_PUBLIC_API_URL = "https://api.twincitiescoverage.com" 