# Cloudflare Pages configuration
pages_build_output_dir = ".next"
build.command = "bash _build.sh"

[build.environment]
NODE_VERSION = "18.12.0"

[environment_variables]
NEXT_PUBLIC_API_URL = "https://api.twincitiescoverage.com" 