version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./templates:/app/templates
      - ./output:/app/output
    environment:
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
    networks:
      - tcc-network

networks:
  tcc-network:
    driver: bridge 