name = "twincitiescoverage-api"
main = "worker/index.js"
compatibility_date = "2023-05-18"

# Configure route for your workers
routes = [
  { pattern = "api.twincitiescoverage.com", custom_domain = true }
]

# Configure environment variables
[vars]
ENVIRONMENT = "production"

# For secrets, use `wrangler secret put SECRET_NAME` to add them 