name = "twincitiescoverage"
main = "worker/index.js"
compatibility_date = "2023-05-18"

# Configure route for your workers
routes = [
  { pattern = "api.twincitiescoverage.com", custom_domain = true }
]

[site]
bucket = ".vercel/output/static" # Next.js static files with cloudflare adapter
entry-point = "."

[build]
command = "npx @cloudflare/next-on-pages"
output_dir = ".vercel/output/static"

# Configure environment variables
[vars]
ENVIRONMENT = "production"

# For secrets, use `wrangler secret put SECRET_NAME` to add them 