name = "twincitiescoverage-api"
main = "worker/index.js"
compatibility_date = "2023-05-18"

# Cloudflare Pages specific configuration
pages_build_output_dir = ".next"

# Configure route for your workers
routes = [
  { pattern = "api.twincitiescoverage.com", custom_domain = true }
]

[site]
bucket = ".next" # Standard Next.js static files

[build]
command = "npm run build"

# Configure environment variables
[vars]
ENVIRONMENT = "production"

# For secrets, use `wrangler secret put SECRET_NAME` to add them 